OpenLDAP 2.3 Change Log
OpenLDAP 2.3.8 Release
	Fixed slapd undef HAVE_EPOLL issue
	Fixed slapd connection-get wake bug (ITS#3999)
	Fixed slapd uninitialized var bug (ITS#3854)
	Fixed slapd add entry without parent bug (ITS#2757)
	Fixed slapd cn=config value escaping bug (ITS#3807)
	Fixed slapd cn=config missing host/uri bug (ITS#4009)
	Fixed slapd alock symbol bug (ITS#3978)
	Fixed slapd replogfile assert (ITS#4003)
	Fixed slapd rewrite session var set bug (ITS#4023)
	Fixed slapd syncrepl empty uniqueMember bug (ITS#4040)
	Fixed slapd alias resolution bug (ITS#4030)
	Fixed slapd password-hash cleartext bug (ITS#4021)
	Fixed slapd realloc zero bug (ITS#3981)
	Fixed slapd nested overlay configuration bug (ITS#4047)
	Fixed slapd password modify oldPassword ignore bug (ITS#4049)
	Added slapd password oldPassword verify (ITS#4051)
	Fixed slapd select_backend manageDSAit with glue issue (ITS#4027)
	Updated slapd authz backend detection (ITS#4018)
	Fixed slapd-bdb/hdb pointer/integer size mismatch (ITS#4015)
	Updated slapd-hdb index management
	Fixed slapd-glue mixtures bug (ITS#3979)
	Fixed slapd-ldap unlock issue (ITS#4001)
	Fixed slapd-ldap manageDIT check bug (ITS#4005)
	Fixed slapd-ldap resource release issue (ITS#4016)
	Fixed slapd-meta rootdn lookup bug (ITS#4004)
	Fixed slapd-meta null value assert issue (ITS#4028)
	Added slapd-meta pooled connections (ITS#4056)
	Added slapd-meta target DSA bind defer when auth'd as rootdn (ITS#4057)
	Fixed slapd-meta pseudorootdn issue
	Fixed slapd-monitor unavailable issue (ITS#4013)
	Fixed slapd-perl init/destroy bug (ITS#3923)
	Fixed slapd-sql missing space issue (ITS#4061)
	Fixed slapo-accesslog timestamp normalization issue
	Fixed slapo-accesslog normalizer issue
	Fixed slapo-ppolicy replication issues (ITS#3980)
	Added slapo-ppolicy pwdattribute descriptor support (ITS#4025)
	Fixed slapo-syncprov/unique interact issues (ITS#3989)
	Fixed slapo-syncprov/subordinate interact issues (ITS#3996)
	Fixed slapo-syncprov schema check assert (ITS#4031)
	Fixed slapo-syncprov psearch flush in qtask
	Fixed slapo-syncprov abandon checks
	Fixed slapo-unique ignore writes not under unique_base (ITS#4066)
	Fixed slapo-valsort unknown valsort-attr bug (ITS#4047)
	Fixed slapcat out-of-memory problem (ITS#4010)
	Fixed slurpd unrecognized slave names bug (ITS#4012)
	Fixed liblber dgram len bug (ITS#4046)
	Fixed libldap SASL and TLS potential ld_error leaks (ITS#4064)
	Fixed liblutil/csn time counter issue
	Updated contrib/ldapc++ to avoid deprecated functions
	Documentation
		Added slapo-valsort(5) man page (ITS#3994)
		Added slap tool -F option documentation (ITS#4026)
	Build Environment
		Fixed misc POSIX conformance issues (ITS#2667)
		Fixed --without-threads build issue (ITS#4006)
		Fixed test script exit checks (ITS#4045)
		Added test suite parameterized directory support
		Fixed test suite tool error handling
		Updated contrib/ldapc++ build environment

OpenLDAP 2.3.7 Release
	Updated slapd ManageDIT support
	Updated slapd ACI syntax checking (ITS#3877)
	Fixed slapd STATS2 referral logging
	Refixed slapd cn=config default search base bug (ITS#3900)
	Fixed slapd cn=config TLSVerifyClient bug (ITS#3962)
	Fixed slapd winsock assert (ITS#3983)
	Fixed slapd-bdb/hdb paged results deadlock (ITS#3940)
	Fixed slapd-bdb/hdb/ldbm searchBase disclose (ITS#3964)
	Fixed slapd-bdb/hdb bi_dbenv check (ITS#3992)
	Fixed slapd-meta generic attribute normalize/pretty (ITS#3956)
	Fixed slapd-ldap/meta 'undefined' attribute mutex protection (ITS#3958)
	Added slapd-ldap/meta 'proxied' attribute support (ITS#3959)
	Fixed slapd-meta no candidate target selected bug (ITS#3990)
	Fixed slapd-meta matchedDN handling (ITS#3944)
	Fixed slapd-monitor hiding issue (ITS#3986)
	Fixed slapo-ppolicy lockout status at Bind (ITS#3946)
	Moved slapo-glue into slapd core
	Fixed slaptest cn=config segfault (ITS#3961)
	Fixed slaptools logging issue (ITS#3937)
	Fixed slaptools fails after db clean (ITS#3970)
	Fixed slaptools reject unsupported -w (ITS#3939)
	Fixed libldap global_opt failure
	Fixed libldap schema handling
	Fixed libldap secprops parsing (ITS#3955)
	Fixed libldap_r tpool (ITS#3925)
	Updated liblutil password scheme check
	Updated libldap schema to allow OID macros in syntaxes
	Removed lint
	Documentation
		Updated misc. man pages
	Build Environment
		Updated build tools (ITS#3928)
		Fixed tests diff -u usage (ITS#3969)
		Fixed slapo-rwm dependency checking (ITS#3965)
		Fixed tests --disable-monitor support
		Fixed tests veryclean-local testdata cleanup
		Add subtree rename test (hdb only)

OpenLDAP 2.3.6 Release
	Fixed slapd dnRelativeMatch return (ITS#3931)
	Fixed slapd send_search_entry issue (ITS#3951)
	Fixed slapd-bdb/hdb release entry in paged response
	Fixed slapd-meta resources release issue (ITS#3943)
	Fixed slapd-ldap/meta matched return (ITS#3942,ITS#3944)
	Fixed slapo-ppolicy reset lockouts issue (ITS#3946)
	Fixed nis.schema posixGroup object class kind (ITS#3941)
	Revert librewrite regex mutex change (ITS#3932)
	Updated slapd manage capability
	Updated slapo-syncprov CSN filter checks
	Updated libldap url list parsing
	Added slapd SASL rootpw support (ITS#3845)
	Added slapd Stats logging for additional cases
	Added slapd ACI syntax validater (ITS#3877)
	Added slapd posixgroup ACL module to contrib
	Added slapi SLAPI_X_ADD_STRUCTURAL_CLASS extension
	Added slapd-ldap subtree renaming proxing
	Added slapd-meta overlapping targets enhancement (ITS#3711)
	Removed lint
	Documentation
		Added slapcat(8) -a usage example (ITS#3930)
		Updated slapo-unique(5) for clarity (ITS#3936)
		Updated slapo-syncprov(5) sessionlog description (ITS#3935)
		Updated doc/drafts
	Build Environment
		Updated test prog bind retry code
		Fixed test015-xsearch regression (ITS#3506)
		Added test040-subtree-rename

OpenLDAP 2.3.5 Release
	Fixed slapd integerBitOr/AndMatch logic (ITS#3782)
	Fixed slapd substrings filter length checks (ITS#3790)
	Fixed slapd thread pool initialization (ITS#3793)
	Fixed slapd cancel exop (ITS#3549)
	Fixed slapd syncrepl cookie problem (ITS#3917)
	Fixed slapd inequality filter index bug (ITS#3920)
	Fixed slapd syncrepl ctxcsn leak (ITS#3922)
	Fixed slapd syncrepl scope issue (ITS#3831)
	Fixed slapd syncrepl missing array subscript (ITS#3834)
	Fixed slapd slapd_remove null deref (ITS#3842)
	Fixed slapd ldapi credential normalization bug (ITS#3876)
	Fixed slapd userPassword cleartext bug (ITS#3846)
	Fixed slapd cn=config default search base bug (ITS#3900)
	Fixed slapd cn=config olcDbConfig bug (ITS#3815)
	Fixed slapd cn=config olcReadOnly bug (ITS#3820)
	Fixed slapd cn=config hdb+bdb bug (ITS#3821)
	Fixed slapd ACL attrs/val EQUALITY issue (ITS#3830)
	Fixed slapd authx-regexp diagnostics (ITS#3819)
	Fixed slapd index_substr_any_step keyword (ITS#3818)
	Fixed slapd -f directory issue (ITS#3865)
	Fixed slapd attributeOptions config parsing (ITS#3829)
	Fixed slapd whitespace config parsing bug (ITS#3901)
	Fixed slapd rootdn space issue (ITS#3806)
	Fixed slapd passwd change w/ {CRYPT} bug (ITS#3805)
	Fixed slapd backend_init_controls assert (ITS#3853)
	Fixed slapd loglevel -1 bug (ITS#3858)
	Fixed slapi bind bound DN issue (ITS#2971)
	Fixed slapi issues (ITS#3884,3885,3886)
	Fixed slapi authorization name issue (ITS#3892)
	Fixed slapi slapi_int_connection_init operation problem (ITS#3868)
	Fixed slapi slapi_entry_has_children bug (ITS#3879)
	Fixed slapd-bdb manual recovery startup (ITS#3607,3824)
	Fixed slapd-bdb manual recovery startup (ITS#3833)
	Fixed slapd-bdb/hdb checkpoint before suffix bug (ITS#3784)
	Fixed slapd-hdb modrdn base bug (ITS#3857)
	Fixed slapd-ldap access to freed connection (ITS#3913)
	Fixed slapd-ldap/meta filter bug (ITS#3785)
	Fixed slapd-ldap/meta connection pooling (ITS#3813)
	Fixed slapd-ldap/meta memory leak (ITS#3862)
	Added slapd-sql enhancements (ITS#3432)
	Fixed slapd-sql attribute with no values issue (ITS#3861)
	Fixed slapd-sql truncating keyval column problem (ITS#3888)
	Fixed slapd-sql return code ignored problem (ITS#3891)
	Fixed slapo-glue alock bug (ITS#3817,3841)
	Fixed slapo-dyngroup hidden subschemaSubentry bug (ITS#3844)
	Fixed slapo-ppolicy hashed length problem (ITS#3783)
	Fixed slapo-ppolicy quality check (ITS#3777)
	Fixed slapo-ppolicy lockout duration (ITS#3779)
	Fixed slapo-rwm leak (ITS#3914)
	Fixed slapo-glue/rwm conflict (ITS#3788)
	Fixed slapadd segfault (ITS#3926)
	Fixed slapcat cn=config segfault (ITS#3796)
	Fixed slaptest -F crash (ITS#3912)
	Fixed slapd authzTo/From syntax issue (ITS#3921)
	Fixed libldap abandon concurrency issue (ITS#3800)
	Fixed libldap start_tls referral chasing (ITS#3791)
	Fixed libldap referral chasing issues (ITS#2894,3578)
	Fixed librewrite concurrency issue (ITS#3932)
	Use IANA-assigned OIDs for recently approved IETF LDAP extensions
	Removed lint (ITS#3857)
	Build Environment
		Upgraded shtool (ITS#3752)
		Upgraded config.guess/config.sub
		Fixed FreeBSD thread stacksize problem (ITS#3456)
		Fixed cygwin shared libraries build problem (ITS#3712)
		Fixed acl_get/acl_mask v AIX symbol clash (ITS#3787)
		Fixed test020 logging problem (ITS#3811)
		Fixed duplicate symbol problem (ITS#3843)
		Fixed liblunicode 64bit builds (ITS#3869)
		Fixed passwd/kerberos module builds (ITS#3896)
		Fixed test037 manageDIT discovery issue (ITS#3898)
		Fixed installed man page symlinks (ITS#3904)
		Fixed <sasl.h> inclusion (ITS#3905)
		Fixed smbk5pwd Heimdal compat issue (ITS#3910)
		Fixed slapd make install issue (ITS#3929)
		Fixed DESTDIR reporting (ITS#3916)
	Documentation
		Fixed Admin Guide authz v. saslauthz problem (ITS#3875)
		Fixed Admin Guide --disable-bdb issue (ITS#3837)
		Fixed slapd-meta(5) lastmod issue (ITS#3789)
		Updated slapd.conf(5) (ITS#3866)
		Updated slapd(8) OPTIONS section (ITS#3816)
		Updated slapd-monitor(5) (ITS#3822,3836)
		Updated slapd-bdb(5) (ITS#3823)

OpenLDAP 2.3.4 Release
	Initial release for "general use".